#ifndef GENSHINCOLCULATORCORE_GLOBAL_H
#define GENSHINCOLCULATORCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GENSHINCOLCULATORCORE_LIBRARY)
#  define GENSHINCOLCULATORCORE_EXPORT Q_DECL_EXPORT
#else
#  define GENSHINCOLCULATORCORE_EXPORT Q_DECL_IMPORT
#endif

#endif // GENSHINCOLCULATORCORE_GLOBAL_H
